services:
  - type: web
    name: businessnet-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromEnvVar: MONGODB_URI
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
      - key: SMTP_PASS
        fromEnvVar: SMTP_PASS
      - key: STRIPE_SECRET_KEY
        fromEnvVar: STRIPE_SECRET_KEY
